### ISSUE TITLE
线形进度条，百分比内显时 Slots 无效

### ISSUE THREAD

**Issue by kele59** [vue-multiple/progress#1]
"vue-multiple-progress": "^1.0.0"
换成环形进度条，或者线形进度条百分比内显时，Slots  才生效。

**Comment by zaxlct** [comment]
线形进度条，百分比内显时 Slots 无效

**Comment by savoygu** [comment]
@zaxlct 已经修改了，更新一下就行了。

**Comment by kele59** [comment]
谢谢作者，非常感谢！
