### ISSUE TITLE
feat：能不能实现多环图

### ISSUE THREAD

**Issue by txs1992** [vue-multiple/progress#10]
如图所示，希望在一个圆中实现多个环。

![image](https://user-images.githubusercontent.com/17583395/48548341-ae1d5180-e907-11e8-8195-89d2ddbca48b.png)

**Comment by savoygu** [comment]
组件不好作支持，推荐你采用[v-charts](https://github.com/ElemeFE/v-charts)，结合这个[示例](https://blog.csdn.net/wlangmood/article/details/78087552)去实现

**Comment by txs1992** [comment]
好的。
