### ISSUE TITLE
Invalid prop: type check failed for prop "percentage". Expected Number, got String.

### ISSUE THREAD

**Issue by miljko1984** [vue-multiple/progress#2]
Thanks in advance.

**Comment by savoygu** [comment]
@miljko1984 Before you pass 'percentage' props，you can make a conversion

**Comment by miljko1984** [comment]
Hello,
I'm returning data from api, my simple code is - :percentage="projects.percentage". And it works well, just got console error message that i reference above.
Thanks

**Comment by savoygu** [comment]
@miljko1984 Already made changes by adding string type for percentage [(https://github.com/vue-multiple/progress/blob/master/src/components/progress.vue#L52)](https://github.com/vue-multiple/progress/blob/master/src/components/progress.vue#L52)，and  it's been posted on npm. In fact, this is not necessary, we can change the type of value passed in by doing something.
