### ISSUE TITLE
stroke-linecap property does not honor 'square' value

### ISSUE THREAD

**Issue by PlkMarudny** [vue-multiple/progress#4]
Seems to render only 'round' line caps

**Comment by savoygu** [comment]
it only works when `type=circle`, if you are in `type= line`, you can set css

**Comment by PlkMarudny** [comment]
Hmm, just looking into sources, indeed, no svg for `line`, fine then. Maybe this should be noted in documentation?

**Comment by savoygu** [comment]
Yes, I did, but there is no relevant English description in the document.

**Comment by PlkMarudny** [comment]
I am not quite sure, but should `border-radius` be set to 0px on vm-progress element?

**Comment by savoygu** [comment]
![image](https://user-images.githubusercontent.com/9302866/38174019-1d4a620e-35f9-11e8-83cf-5f56dbc02d4d.png)
need set `class="vm-progress-bar__outer"` and `class="vm-progress-bar__inner"`'s `border-radius=0px`

**Comment by PlkMarudny** [comment]
Nailed it, thank you. Don;t you think that eventually a SVG path could be used instead here? Properties applied to a circle would be transferrable to this case as well.

**Comment by savoygu** [comment]
I have considered this, but the position of the ʻinnerText` is not well controlled. Based on this, I can apply effects like `type=circle` to `type=line`, for example: `stroke-linecap`, `reverse`
