### ISSUE TITLE
status 改变后，颜色没有重新渲染。

### ISSUE THREAD

**Issue by txs1992** [vue-multiple/progress#8]
status 改变后，颜色没有重新渲染。

https://jsfiddle.net/_MT_/eywraw8t/398037/

**Comment by savoygu** [comment]
刚发布了一个版本，可以更新一下包，示例代码可以参考：
https://vue-multiple.github.io/progress/#zhuang-tai-qie-huan

**Comment by txs1992** [comment]
👌非常感谢。
