### ISSUE TITLE
Component is not responsive

### ISSUE THREAD

**Issue by stelgenhof** [vue-multiple/progress#9]
The component currently used 'px' for the width and height of its size. As you may know, you can use 'vh' / 'vw' as the unit of measure for the dimensions in CSS as well. (vh = size as a ratio of the viewport height, vw = size as a ratio of the viewport width).

Using vh/vw makes it perfectly resizable when using different screen sizes. Unfortunately the 'px' definition in the component makes it not possible to become responsive. Also I tried to override the CSS class however the style attribute takes precedence, so that is not a solution either.

Hopefully you could consider changing this.

Cheers! Sacha

**Comment by savoygu** [comment]
yeah, but some data(relativeStrokeWidth, progressTextSize) dependence the width, if using 'vw' / 'vh' to realize, these data not very good control, so directly modify style is a good option.

**Comment by stelgenhof** [comment]
@savoygu Yes, you are right. I found already the possibility to override the styles. Works perfectly! 
And adding a outer container makes the component responsive as well.

Thanks again for the nice component.
